services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations/ddl:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: api_app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

  conciliatejob:
    build:
      context: .
      dockerfile: docker/conciliatejob/Dockerfile
    container_name: conciliatejob_app
    depends_on:
      - db

  reportjob:
    build:
      context: .
      dockerfile: docker/reportjob/Dockerfile
    container_name: reportjob
    depends_on:
      - db

volumes:
  mysql_data:
